### PR TITLE
Fix for updated fflib-apex-common

### PR DESCRIPTION
**Pull request by wimvelzeboer**

### CODE REVIEW

**Comment by dfuller114** [comment]
@wimvelzeboer just to understand some of the change here. Were there some interfaces in the extensions package that were introduced in the apex-common library instead and creating duplicates?

**Comment by wimvelzeboer** [comment]
@dfuller114  The main thing that is changed is that a lot of domain methods and the Application Factory interfaces were moved from the fflib-apex-extensions repo to fflib-apex-common. There were a few small changes, like the setMock method on the Application factories interfaces are back to private.

**Comment by dfuller114** [comment]
@wimvelzeboer Thanks. I'm trying to look at the best way to utilize the dynamic app binding without using CMT records. The best way appeared to be using the backward compatible classic interfaces. However, each classic interface implements `fflib_IServiceFactory`, `fflib_IDomainFactory`, etc which have now been moved up to apex commons.

These classic factories such as `fflib_ClassicDomainFactory` don't compile for me right now because there are a few `newInstance()` methods declared on the factory interfaces in apex-commons that are not implemented on these classic factories. For example, `fflib_ClassicDomainFactory` implements `fflib_IDomainFactory` but that factory interface has four `newInstance()` methods declared but `fflib_ClassicDomainFactory` only implements two `newInstance()` methods. Is there something I'm missing here?

**Comment by wimvelzeboer** [comment]
@dfuller114 Indeed, if you do not want to use the Custom Metadata records, then the Classic Application Factories are the best choice. It offers basically the same functionality at run-time.

When the Application factory interfaces were moved to fflib-apex-commons some of the method signatures were removed.

The removed method signatures for `fflib_IDomainFactory` are :

`fflib_IDomain newInstance(Set<Id> recordIds, Schema.SObjectType sObjectType);`
`void setMock(fflib_ISObjectDomain mockDomain);`

>  For example, fflib_ClassicDomainFactory implements fflib_IDomainFactory but that factory interface has four newInstance() methods declared but fflib_ClassicDomainFactory only implements two newInstance() methods. Is there something I'm missing here?

There are indeed now only two `newInstance` methods implemented in `fflib_ClassicDomainFactory`, the other two which are defined in the interface, are implemented in the `fflib_Application.DomainFactory` class. Those two method are inherited by `fflib_ClassicDomainFactory` as its extended from `fflib_Application.DomainFactory`.

I am not sure why it does not compile for you, but I am getting the idea that you also need to update the fflib-apex-common in your project. If I do a check out of this repo, create a scratch org, deploy apex-mocks & apex-common and then this repo, then every compiles perfectly.

Can you maybe share the exact compilation error message that you are getting?

**Pull request merged**
